name = "cloudflared-relay"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[observability]
enabled = true

[[kv_namespaces]]
binding = "RELAY_KV"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
